=== ChrysalideFI/BatailleNavale/Bataille/validationgrille.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!--peut-Ãªtre ajouter un truc sur le fait que les bateaux se supperoposent pas-->
  <xs:element name="batailleNavale">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="grille" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ligne" maxOccurs="10">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="case" maxOccurs="10">
                      <xs:complexType>
                        <xs:attribute name="coord" type="xs:string" use="required"/>
                        <xs:attribute name="etat" type="etatCase" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Flotte du joueur -->
        <xs:element name="flotte" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="bateau" maxOccurs="10">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="position" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="coord" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="typeBateau" use="required"/>
                  <xs:attribute name="etat" type="etatBateau" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Etat cases -->
  <xs:simpleType name="etatCase">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vide"/>
      <xs:enumeration value="touche"/>
      <xs:enumeration value="eau"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Types de bateaux bateaux -->
  <xs:simpleType name="typeBateau">
    <xs:restriction base="xs:string">
      <xs:enumeration value="porte-avions"/>
      <xs:enumeration value="croiseur"/>
      <xs:enumeration value="contre-torpilleur"/>
      <xs:enumeration value="sous-marin"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Etat des bateaux -->
  <xs:simpleType name="etatBateau">
    <xs:restriction base="xs:string">
      <xs:enumeration value="intact"/>
      <xs:enumeration value="touche"/>
      <xs:enumeration value="coule"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ChrysalideFI/BatailleNavale/Bataille/bateauxplacés.xml
<?xml version="1.0" encoding="UTF-8"?>
<batailleNavale xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="validationgrille.xsd">
  <!-- Grille du joueur -->
  <grille>
    <ligne>
      <case coord="A1" etat="vide"/>
      <case coord="A2" etat="vide"/>
      <case coord="A3" etat="vide"/>
      <case coord="A4" etat="vide"/>
      <case coord="A5" etat="vide"/>
      <case coord="A6" etat="vide"/>
      <case coord="A7" etat="vide"/>
      <case coord="A8" etat="vide"/>
      <case coord="A9" etat="vide"/>
      <case coord="A10" etat="vide"/>
    </ligne>
    <ligne>
      <case coord="B1" etat="vide"/>
      <case coord="B2" etat="vide"/>
      <case coord="B3" etat="vide"/>
      <case coord="B4" etat="vide"/>
      <case coord="B5" etat="vide"/>
      <case coord="B6" etat="vide"/>
      <case coord="B7" etat="vide"/>
      <case coord="B8" etat="vide"/>
      <case coord="B9" etat="vide"/>
      <case coord="B10" etat="vide"/>
    </ligne>
      <ligne>
      <case coord="C1" etat="vide"/>
      <case coord="C2" etat="vide"/>
      <case coord="C3" etat="vide"/>
      <case coord="C4" etat="vide"/>
      <case coord="C5" etat="vide"/>
      <case coord="C6" etat="vide"/>
      <case coord="C7" etat="vide"/>
      <case coord="C8" etat="vide"/>
      <case coord="C9" etat="vide"/>
      <case coord="C10" etat="vide"/>
    </ligne>
      <ligne>
      <case coord="D1" etat="vide"/>
      <case coord="D2" etat="vide"/>
      <case coord="D3" etat="vide"/>
      <case coord="D4" etat="vide"/>
      <case coord="D5" etat="vide"/>
      <case coord="D6" etat="vide"/>
      <case coord="D7" etat="vide"/>
      <case coord="D8" etat="vide"/>
      <case coord="D9" etat="vide"/>
      <case coord="D10" etat="vide"/>
    </ligne>
      <ligne>
      <case coord="E1" etat="vide"/>
      <case coord="E2" etat="vide"/>
      <case coord="E3" etat="vide"/>
      <case coord="E4" etat="vide"/>
      <case coord="E5" etat="vide"/>
      <case coord="E6" etat="vide"/>
      <case coord="E7" etat="vide"/>
      <case coord="E8" etat="vide"/>
      <case coord="E9" etat="vide"/>
      <case coord="E10" etat="vide"/>
    </ligne>
      <ligne>
      <case coord="F1" etat="vide"/>
      <case coord="F2" etat="vide"/>
      <case coord="F3" etat="vide"/>
      <case coord="F4" etat="vide"/>
      <case coord="F5" etat="vide"/>
      <case coord="F6" etat="vide"/>
      <case coord="F7" etat="vide"/>
      <case coord="F8" etat="vide"/>
      <case coord="F9" etat="vide"/>
      <case coord="F10" etat="vide"/>
    </ligne>
      <ligne>
      <case coord="G1" etat="vide"/>
      <case coord="G2" etat="vide"/>
      <case coord="G3" etat="vide"/>
      <case coord="G4" etat="vide"/>
      <case coord="G5" etat="vide"/>
      <case coord="G6" etat="vide"/>
      <case coord="G7" etat="vide"/>
      <case coord="G8" etat="vide"/>
      <case coord="G9" etat="vide"/>
      <case coord="G10" etat="vide"/>
    </ligne>
          <ligne>
      <case coord="H1" etat="vide"/>
      <case coord="H2" etat="vide"/>
      <case coord="H3" etat="vide"/>
      <case coord="H4" etat="vide"/>
      <case coord="H5" etat="vide"/>
      <case coord="H6" etat="vide"/>
      <case coord="H7" etat="vide"/>
      <case coord="H8" etat="vide"/>
      <case coord="H9" etat="vide"/>
      <case coord="H10" etat="vide"/>
    </ligne>      <ligne>
      <case coord="I1" etat="vide"/>
      <case coord="I2" etat="vide"/>
      <case coord="I3" etat="vide"/>
      <case coord="I4" etat="vide"/>
      <case coord="I5" etat="vide"/>
      <case coord="I6" etat="vide"/>
      <case coord="I7" etat="vide"/>
      <case coord="I8" etat="vide"/>
      <case coord="I9" etat="vide"/>
      <case coord="I10" etat="vide"/>
    </ligne>      <ligne>
      <case coord="J1" etat="vide"/>
      <case coord="J2" etat="vide"/>
      <case coord="J3" etat="vide"/>
      <case coord="J4" etat="vide"/>
      <case coord="J5" etat="vide"/>
      <case coord="J6" etat="vide"/>
      <case coord="J7" etat="vide"/>
      <case coord="J8" etat="vide"/>
      <case coord="J9" etat="vide"/>
      <case coord="J10" etat="vide"/>
    </ligne>
  </grille>
  <!-- Flotte de bateaux -->
  <flotte>
    <bateau type="porte-avions" etat="intact">
      <position coord="F10"/>
      <position coord="G10"/>
      <position coord="H10"/>
      <position coord="I10"/>
      <position coord="J10"/>
    </bateau>
    <bateau type="croiseur" etat="intact">
      <position coord="A3"/>
      <position coord="A4"/>
      <position coord="A5"/>
      <position coord="A6"/>
    </bateau>
    <bateau type="croiseur" etat="intact">
      <position coord="G1"/>
      <position coord="H1"/>
      <position coord="I1"/>
      <position coord="J1"/>
    </bateau>
    <bateau type="contre-torpilleur" etat="intact">
      <position coord="D1"/>
      <position coord="D2"/>
      <position coord="D3"/>
    </bateau>
        <bateau type="contre-torpilleur" etat="intact">
      <position coord="F3"/>
      <position coord="G3"/>
      <position coord="H3"/>
    </bateau>
        <bateau type="contre-torpilleur" etat="intact">
      <position coord="J6"/>
      <position coord="J7"/>
      <position coord="J8"/>
    </bateau>
    <bateau type="sous-marin" etat="intact">
      <position coord="A1"/>
      <position coord="B1"/>
    </bateau>
        <bateau type="sous-marin" etat="intact">
      <position coord="F6"/>
      <position coord="F7"/>
    </bateau>
        <bateau type="sous-marin" etat="intact">
      <position coord="A8"/>
      <position coord="B8"/>
    </bateau>
        <bateau type="sous-marin" etat="intact">
      <position coord="J3"/>
      <position coord="J4S"/>
    </bateau>
  </flotte>
</batailleNavale>
